//
// Created by vara on 08.10.2020.
//

#ifndef IMMORTAL_STACK_HELP_STACK_H
#define IMMORTAL_STACK_HELP_STACK_H

#define ERROR 42
const void * ERROR_PTR;
#define ERROR_TYPE(X) #X

enum STACK_ERRORS{
    STACK_OK,
    STACK_NULL_POINTER,
    STACK_BAD_CALLOC,
    STACK_EMPTY,
    STACK_FULL,
    STACK_BAD_SIZE,
    STACK_BAD_CAPACITY,
    STACK_NULL_STORAGE,
    STACK_ERRPTR_STORAGE,

};

#endif //IMMORTAL_STACK_HELP_STACK_H
