#ifndef IMMORTAL_STACK_STACK_ERRORS_H
#define IMMORTAL_STACK_STACK_ERRORS_H

#define ERROR 42
const void * ERROR_PTR;
#define GET_TYPE(X) #X

enum STACK_ERRORS{
    STACK_OK,
    STACK_NULL_POINTER,
    STACK_BAD_SIZE,
    STACK_BAD_CAPACITY,
    STACK_NULL_STORAGE,
    STACK_ERRPTR_STORAGE,
    STACK_LEFT_CANARY_SONGS,
    STACK_RIGHT_CANARY_SONGS,
    STACK_ALL_CANARY_SONGS,
    STACK_BUFFER_CANARY_LEFT_SONGS,
    STACK_BUFFER_CANARY_RIGHT_SONGS
};

#endif //IMMORTAL_STACK_STACK_ERRORS_H
